# Generated by Django 3.2 on 2021-05-25 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('mobile', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('textmsg', models.CharField(max_length=500)),
            ],
        ),
    ]
