# Generated by Django 3.2 on 2021-05-25 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User_register',
            new_name='Register',
        ),
    ]
