# Generated by Django 3.2 on 2021-05-26 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20210525_2350'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='r_Email',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='r_Password',
            new_name='Password',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='r_Phone',
            new_name='Phone',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='r_name',
            new_name='name',
        ),
    ]
